<?php
    //services
    echo "scalar config: ". print_r($this->configScalar,true)."<br>";
    echo "array config : ". print_r($this->configArray, true)."<br>";
    
    //invokables
    /*echo "user 1       : ";
    var_dump($this->user1);
    echo "<br>user 2      : ";
    var_dump($this->user2);
    echo "<br>user manager:";
    var_dump($this->userManager);
    echo "<br>mail manager:";
    var_dump($this->mailManager);
    
    echo "<br>profile 1   : ";
    var_dump($this->profile1);
    echo "<br>profile 2   : ";
    var_dump($this->profile2);*/
    
    